sudo: required
language: c

os: linux
dist: xenial

env:
 - GHCVER=7.10.3
 - GHCVER=8.0.2
 - GHCVER=8.2.2
 - GHCVER=8.4.4
 - GHCVER=8.6.5
 - GHCVER=8.8.1

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install alex-3.1.7 happy-1.19.5 cabal-install-3.0 ghc-$GHCVER
 - export PATH=/opt/cabal/bin:/opt/ghc/$GHCVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH

install:
 - cabal-3.0 update

script:
 - cabal-3.0 configure --enable-tests
 - cabal-3.0 build
 - cabal-3.0 test --test-show-details=streaming
 - cabal-3.0 check
 - cabal-3.0 haddock
 - cabal-3.0 sdist
