# language: haskell

# See http://www.reddit.com/r/haskell/comments/1os3f6/how_to_use_travisci_with_multiple_ghc_versions/

env:
 - GHCVER=7.6.3
 - GHCVER=7.8.4
 - GHCVER=7.10.3
 - GHCVER=8.0.1

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.22 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.24 update
 - cabal-1.24 install happy
 - cabal-1.24 install alex
 - cabal-1.24 install --only-dependencies --enable-tests;

script:
 - cabal-1.24 configure --enable-tests
 - cabal-1.24 build
 - dist/build/testsuite/testsuite
 - cabal-1.24 check
 - cabal-1.24 haddock
 - cabal-1.24 sdist
