# language: haskell

# See http://www.reddit.com/r/haskell/comments/1os3f6/how_to_use_travisci_with_multiple_ghc_versions/

env:
 - GHCVER=7.10.3
 - GHCVER=8.0.2
 - GHCVER=8.2.2
 - GHCVER=8.4.4
 - GHCVER=8.6.2

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install alex-3.1.7 happy-1.19.5 cabal-install-1.24 ghc-$GHCVER
 - export PATH=/opt/cabal/bin:/opt/ghc/$GHCVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH

install:
 - cabal-1.24 update
 - cabal-1.24 install --only-dependencies --enable-tests;

script:
 - cabal-1.24 configure --enable-tests
 - cabal-1.24 build
 - dist/build/testsuite/testsuite
 - cabal-1.24 check
 - cabal-1.24 haddock
 - cabal-1.24 sdist
